FROM bitnami/node:16.17.0

RUN mkdir -p /app
WORKDIR /app

COPY ["package.json", "yarn.lock", "/app/"]
RUN yarn

COPY . /app

RUN yarn build

ENV NODE_ENV development
ENV PORT 3001
ENV NUXT_PORT 3001
ENV NEST_PORT 3001

CMD ["node", "/app/node_modules/.bin/nest", "start", "--watch"]
